### ISSUE TITLE
Getting error: "Pulling manifest. Error: pull model manifest: model not found"

### ISSUE THREAD

**Issue by kotpal** [lrvl/ollama-twice#1]
I pulled "ollama pull llama2" and got the model installed. Even then I am getting the above error. What model are you pulling? And how can I resolve this error?

**Comment by lrvl** [comment]
Hi @kotpal 

Please `git pull` the new version which requires the model name as last argument. In your case use:

```
# In shell / window one
./ollama_twice.sh A pipe1 pipe2 llama2
# In shell / window two
./ollama_twice.sh B pipe2 pipe1 llama2
```

After that start it with for example:
```
# In shell / window three
echo "Pick a random topic" > pipe1
```
